# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4d6b8ad1cdc40ba5ad2f445ad6594f0"
name = "ai-caller"
handle = "ai-caller"
application_url = "https://teaching-hits-classic-experimental.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "productassist.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products read_customers read_inventory"

[auth]
redirect_urls = [
  "https://teaching-hits-classic-experimental.trycloudflare.com/auth/callback",
  "https://teaching-hits-classic-experimental.trycloudflare.com/auth/shopify/callback",
  "https://teaching-hits-classic-experimental.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
